Django_React_Langchain_Stream/urls.py
from django.contrib import admin
from django.urls import path, include
import core.views as views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('docs/',include('langchain_stream.urls')),
    path('convs/',include('langchain_chat.urls')),
    path('accounts/', include('allauth.urls')),
    path('', views.HomeView.as_view(), name='home'),
    path('contact/', views.ContactView.as_view(), name='contact'),
    path('profile/', views.ProfileView.as_view(), name='profile'),
    path('ml/', include('ml.urls', namespace='ml')),
]

ml/urls.py
from django.urls import path

from . import views
from . import chart_views

app_name = 'ml'

urlpatterns = [

    path('data_preparation/', views.render_prep, name='data_preparation'),
    path('notebook-prep/', views.notebook_prep, name='notebook-prep'),

    path('adaboost/', views.render_adaboost, name='adaboost'),
    path('notebook-ada/', views.notebook_adaboost, name='notebook-ada'),

    path('summary/', views.render_summary, name='summary'),
    path('notebook-summary/', views.notebook_summary, name='notebook-summary'),

    path('bayess/', views.render_bayess, name='bayess'),
    path('notebook-bayess/', views.notebook_bayess, name='notebook-bayess'),

    path('kneighbours/', views.render_kn, name='kneighbours'),
    path('notebook-kn/', views.notebook_kn, name='notebook-kn'),

    path('decision-tree/', views.render_tree, name='decision-tree'),
    path('notebook-tree/', views.notebook_tree, name='notebook-tree'),

    path('random-forest/', views.render_rf, name='random-forest'),
    path('notebook-forest/', views.notebook_rf, name='notebook-forest'),

    path('svc/', views.render_svc, name='svc'),
    path('notebook-svc/', views.notebook_svc, name='notebook-svc'),

    path('grid/', views.render_grid, name='grid'),
    path('notebook-grid/', views.notebook_grid, name='notebook-grid'),

    path('ada-reg/', views.render_ada_reg, name='ada-reg'),
    path('notebook-ada-reg/', views.notebook_ada_reg, name='notebook-ada-reg'),

    path('lasso/', views.render_lasso, name='lasso'),
    path('notebook-lasso/', views.notebook_lasso, name='notebook-lasso'),

    path('lr/', views.render_lr, name='lr'),
    path('notebook-lr/', views.notebook_lr, name='notebook-lr'),

    path('summary-reg/', views.render_summary_reg, name='summary-reg'),
    path('notebook-summary-reg/', views.notebook_summary_reg, name='notebook-summary-reg'),

    path('ridge/', views.render_ridge, name='ridge'),
    path('notebook-ridge/', views.notebook_ridge, name='notebook-ridge'),

    path('unsuperv-prep/', views.render_prep_reg, name='prep-reg'),
    path('notebook-prep-reg/', views.notebook_prep_reg, name='notebook-prep-reg'),

    path('eval-ksn/', views.render_eval_ksn, name='eval-ksn'),
    path('notebook-eval-ksn/', views.notebook_eval_ksn, name='notebook-eval-ksn'),

    path('model-ksn/', views.render_model_ksn, name='model-ksn'),
    path('notebook-model-ksn/', views.notebook_model_ksn, name='notebook-model-ksn'),

    path('prep-ksn/', views.render_prep_ksn, name='prep-ksn'),
    path('notebook-prep-ksn/', views.notebook_prep_ksn, name='notebook-prep-ksn'),

    path('db-agglo-km/', views.render_dbagglokm, name='db-agglo-km'),
    path('notebook-db-agglo-km/', views.notebook_dbagglokm, name='notebook-db-agglo-km'),
    path('charts-KMclustDB/', chart_views.serve_chart1, name='charts-KMclustDB'),
    path('charts-KMclustDB2/', chart_views.serve_chart2, name='charts-KMclustDB2'),
    path('charts-KMclustDB3/', chart_views.serve_chart3, name='charts-KMclustDB3'),
    path('charts-KMclustDB4/', chart_views.serve_chart4, name='charts-KMclustDB4'),

    path('pca/', views.render_pca, name='pca'),
    path('notebook-pca/', views.notebook_pca, name='notebook-pca'),

    path('tsne/', views.render_tsne, name='tsne'),
    path('notebook-tsne/', views.notebook_tsne, name='notebook-tsne'),
    path('charts-tsne1/', chart_views.serve_chart_tsne1, name='charts-tsne1'),
    path('charts-tsne2/', chart_views.serve_chart_tsne2, name='charts-tsne2'),
    path('charts-tsne3/', chart_views.serve_chart_tsne3, name='charts-tsne3'),
    path('charts-tsne4/', chart_views.serve_chart_tsne4, name='charts-tsne4'),
    path('charts-tsne5/', chart_views.serve_chart_tsne5, name='charts-tsne5'),
    path('charts-tsne6/', chart_views.serve_chart_tsne6, name='charts-tsne6'),
    path('charts-tsne7/', chart_views.serve_chart_tsne7, name='charts-tsne7'),

    path('apriori/', views.render_apriori, name='apriori'),
    path('notebook-apriori/', views.notebook_apriori, name='notebook-apriori'),

    path('isoforest/', views.render_isoforest, name='isoforest'),
    path('notebook-isoforest/', views.notebook_isoforest, name='notebook-isoforest'),

    path('lof/', views.render_lof, name='lof'),
    path('notebook-lof/', views.notebook_lof, name='notebook-lof'),

    path('gan-param/', views.render_gan_param, name='gan-param'),
    path('notebook-gan-param/', views.notebook_gan_param, name='notebook-gan-param'),

    path('gan-gp/', views.render_gan_gp, name='gan-gp'),
    path('notebook-gan-gp/', views.notebook_gan_gp, name='notebook-gan-gp'),

    path('gan-loop/', views.render_gan_loop, name='gan-loop'),
    path('notebook-gan-loop/', views.notebook_gan_loop, name='notebook-gan-loop'),

]

ml/models.py
from django.db import models

# Create your models here.

ml/views.py
from django.shortcuts import render
import os
from django.http import HttpResponse

def render_prep(request):
    return render(request, 'ml/superv_class/data_preparation.html')

def notebook_prep(request):
    # Serve the notebook HTML file
    notebook_file_path = os.path.join('static', 'notebooks/data_preparation.html')
    with open(notebook_file_path, 'r', encoding='utf-8') as f:
        notebook_html = f.read()
    return HttpResponse(notebook_html)


def render_adaboost(request):
    return render(request, 'ml/superv_class/adaboost.html')

def notebook_adaboost(request):
    # Serve the notebook HTML file
    notebook_file_path = os.path.join('static', 'notebooks/adaboost.html')
    with open(notebook_file_path, 'r', encoding='utf-8') as f:
        notebook_html = f.read()
    return HttpResponse(notebook_html)


def render_kn(request):
    return render(request, 'ml/superv_class/kn.html')

def notebook_kn(request):
    # Serve the notebook HTML file
    notebook_file_path = os.path.join('static', 'notebooks/KN.html')
    with open(notebook_file_path, 'r', encoding='utf-8') as f:
        notebook_html = f.read()
    return HttpResponse(notebook_html)


def render_svc(request):
    return render(request, 'ml/superv_class/svc.html')

def notebook_svc(request):
    # Serve the notebook HTML file
    notebook_file_path = os.path.join('static', 'notebooks/SVC.html')
    with open(notebook_file_path, 'r', encoding='utf-8') as f:
        notebook_html = f.read()
    return HttpResponse(notebook_html)


def render_tree(request):
    return render(request, 'ml/superv_class/tree.html')

def notebook_tree(request):
    # Serve the notebook HTML file
    notebook_file_path = os.path.join('static', 'notebooks/tree.html')
    with open(notebook_file_path, 'r', encoding='utf-8') as f:
        notebook_html = f.read()
    return HttpResponse(notebook_html)


def render_rf(request):
    return render(request, 'ml/superv_class/rf.html')

def notebook_rf(request):
    # Serve the notebook HTML file
    notebook_file_path = os.path.join('static', 'notebooks/RF.html')
    with open(notebook_file_path, 'r', encoding='utf-8') as f:
        notebook_html = f.read()
    return HttpResponse(notebook_html)


def render_bayess(request):
    return render(request, 'ml/superv_class/bayes.html')

def notebook_bayess(request):
    # Serve the notebook HTML file
    notebook_file_path = os.path.join('static', 'notebooks/bayess.html')
    with open(notebook_file_path, 'r', encoding='utf-8') as f:
        notebook_html = f.read()
    return HttpResponse(notebook_html)


def render_summary(request):
    return render(request, 'ml/superv_class/summary.html')

def notebook_summary(request):
    # Serve the notebook HTML file
    notebook_file_path = os.path.join('static', 'notebooks/summary.html')
    with open(notebook_file_path, 'r', encoding='utf-8') as f:
        notebook_html = f.read()
    return HttpResponse(notebook_html)


def render_ada_reg(request):
    return render(request, 'ml/superv_reg/ada_reg.html')

def notebook_ada_reg(request):
    # Serve the notebook HTML file
    notebook_file_path = os.path.join('static', 'notebooks/ada-reg.html')
    with open(notebook_file_path, 'r', encoding='utf-8') as f:
        notebook_html = f.read()
    return HttpResponse(notebook_html)


def render_ridge(request):
    return render(request, 'ml/superv_reg/ridge.html')

def notebook_ridge(request):
    # Serve the notebook HTML file
    notebook_file_path = os.path.join('static', 'notebooks/ridge.html')
    with open(notebook_file_path, 'r', encoding='utf-8') as f:
        notebook_html = f.read()
    return HttpResponse(notebook_html)


def render_lr(request):
    return render(request, 'ml/superv_reg/lr.html')

def notebook_lr(request):
    # Serve the notebook HTML file
    notebook_file_path = os.path.join('static', 'notebooks/lr.html')
    with open(notebook_file_path, 'r', encoding='utf-8') as f:
        notebook_html = f.read()
    return HttpResponse(notebook_html)


def render_lasso(request):
    return render(request, 'ml/superv_reg/lasso.html')

def notebook_lasso(request):
    # Serve the notebook HTML file
    notebook_file_path = os.path.join('static', 'notebooks/lasso.html')
    with open(notebook_file_path, 'r', encoding='utf-8') as f:
        notebook_html = f.read()
    return HttpResponse(notebook_html)


def render_grid(request):
    return render(request, 'ml/superv_reg/grid.html')

def notebook_grid(request):
    # Serve the notebook HTML file
    notebook_file_path = os.path.join('static', 'notebooks/grid_search.html')
    with open(notebook_file_path, 'r', encoding='utf-8') as f:
        notebook_html = f.read()
    return HttpResponse(notebook_html)


def render_summary_reg(request):
    return render(request, 'ml/superv_reg/summary_reg.html')

def notebook_summary_reg(request):
    # Serve the notebook HTML file
    notebook_file_path = os.path.join('static', 'notebooks/summary_reg.html')
    with open(notebook_file_path, 'r', encoding='utf-8') as f:
        notebook_html = f.read()
    return HttpResponse(notebook_html)


def render_prep_reg(request):
    return render(request, 'ml/superv_reg/prep.html')

def notebook_prep_reg(request):
    # Serve the notebook HTML file
    notebook_file_path = os.path.join('static', 'notebooks/unsuperv_prep.html')
    with open(notebook_file_path, 'r', encoding='utf-8') as f:
        notebook_html = f.read()
    return HttpResponse(notebook_html)


def render_prep_ksn(request):
    return render(request, 'ml/ksn/prep.html')

def notebook_prep_ksn(request):
    # Serve the notebook HTML file
    notebook_file_path = os.path.join('static', 'notebooks/KSN_prep.html')
    with open(notebook_file_path, 'r', encoding='utf-8') as f:
        notebook_html = f.read()
    return HttpResponse(notebook_html)


def render_model_ksn(request):
    return render(request, 'ml/ksn/model.html')

def notebook_model_ksn(request):
    # Serve the notebook HTML file
    notebook_file_path = os.path.join('static', 'notebooks/KSN_model.html')
    with open(notebook_file_path, 'r', encoding='utf-8') as f:
        notebook_html = f.read()
    return HttpResponse(notebook_html)


def render_eval_ksn(request):
    return render(request, 'ml/ksn/eval.html')

def notebook_eval_ksn(request):
    # Serve the notebook HTML file
    notebook_file_path = os.path.join('static', 'notebooks/KSN_eval.html')
    with open(notebook_file_path, 'r', encoding='utf-8') as f:
        notebook_html = f.read()
    return HttpResponse(notebook_html)


def render_dbagglokm(request):
    return render(request, 'ml/unsuperv/dbagglokm.html')

def notebook_dbagglokm(request):
    # Serve the notebook HTML file
    notebook_file_path = os.path.join('static', 'notebooks/DBclustKM.html')
    with open(notebook_file_path, 'r', encoding='utf-8') as f:
        notebook_html = f.read()
    return HttpResponse(notebook_html)


def render_pca(request):
    return render(request, 'ml/unsuperv/pca.html')

def notebook_pca(request):
    # Serve the notebook HTML file
    notebook_file_path = os.path.join('static', 'notebooks/PCA.html')
    with open(notebook_file_path, 'r', encoding='utf-8') as f:
        notebook_html = f.read()
    return HttpResponse(notebook_html)


def render_tsne(request):
    return render(request, 'ml/unsuperv/tsne.html')

def notebook_tsne(request):
    # Serve the notebook HTML file
    notebook_file_path = os.path.join('static', 'notebooks/tsne.html')
    with open(notebook_file_path, 'r', encoding='utf-8') as f:
        notebook_html = f.read()
    return HttpResponse(notebook_html)


def render_apriori(request):
    return render(request, 'ml/unsuperv/apriori.html')

def notebook_apriori(request):
    # Serve the notebook HTML file
    notebook_file_path = os.path.join('static', 'notebooks/apriori.html')
    with open(notebook_file_path, 'r', encoding='utf-8') as f:
        notebook_html = f.read()
    return HttpResponse(notebook_html)


def render_isoforest(request):
    return render(request, 'ml/unsuperv/forest.html')

def notebook_isoforest(request):
    # Serve the notebook HTML file
    notebook_file_path = os.path.join('static', 'notebooks/isoforest.html')
    with open(notebook_file_path, 'r', encoding='utf-8') as f:
        notebook_html = f.read()
    return HttpResponse(notebook_html)


def render_lof(request):
    return render(request, 'ml/unsuperv/lof.html')

def notebook_lof(request):
    # Serve the notebook HTML file
    notebook_file_path = os.path.join('static', 'notebooks/lof.html')
    with open(notebook_file_path, 'r', encoding='utf-8') as f:
        notebook_html = f.read()
    return HttpResponse(notebook_html)


def render_gan_param(request):
    return render(request, 'ml/gan/gan-param.html')

def notebook_gan_param(request):
    # Serve the notebook HTML file
    notebook_file_path = os.path.join('static', 'notebooks/GAN_models.html')
    with open(notebook_file_path, 'r', encoding='utf-8') as f:
        notebook_html = f.read()
    return HttpResponse(notebook_html)


def render_gan_gp(request):
    return render(request, 'ml/gan/gan-gp.html')

def notebook_gan_gp(request):
    # Serve the notebook HTML file
    notebook_file_path = os.path.join('static', 'notebooks/GAN_gp.html')
    with open(notebook_file_path, 'r', encoding='utf-8') as f:
        notebook_html = f.read()
    return HttpResponse(notebook_html)


def render_gan_loop(request):
    return render(request, 'ml/gan/gan-loop.html')

def notebook_gan_loop(request):
    # Serve the notebook HTML file
    notebook_file_path = os.path.join('static', 'notebooks/GAN_loop.html')
    with open(notebook_file_path, 'r', encoding='utf-8') as f:
        notebook_html = f.read()
    return HttpResponse(notebook_html)

templates/ml/unsuperv/apriori.html
{% extends "base.html" %}
{% load static %}

{% block content %}

    <div class="site-section notebook-dark-theme">
        
        <div class="container-wrapper">
            <!-- Sidebar section -->
            <div class="sidebar-container">
                {% include 'sidebar.html' %}
                </div>
            <!-- Main content section -->
            <div class="content-section">
                <div class="container">
                    <div class="row justify-content-center">
                        <div class="col-md-9">
                            <h2 class="h3 mb-3">Python Code Example</h2>
                            <div id="notebook-container" class="notebook-card">
                                <!-- Notebook content will be injected here -->
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>


<script>
    document.addEventListener('DOMContentLoaded', function() {
        // Use AJAX to fetch the notebook HTML and inject it into the div
        fetch("{% url 'ml:notebook-apriori' %}")
            .then(response => response.text())
            .then(html => {
                document.getElementById('notebook-container').innerHTML = html;

                // Apply dark theme CSS after notebook is loaded
                applyDarkTheme();
            })
            .catch(error => {
                console.error('Error fetching notebook HTML:', error);
            });
    });


    function applyDarkTheme() {
        // Add specific dark theme styles for the notebook
        const style = document.createElement('style');
        style.innerHTML = `
            /* Dark Theme Styling for Notebook */
            .notebook-dark-theme {
                background-color: #1e1e1e;
                color: #dcdcdc !important;
                padding: 20px;
                border-radius: 10px;
                box-shadow: 0 4px 8px rgba(0, 0, 0, 0.3);
                transition: all 0.3s ease-in-out;
                overflow: hidden;
                font-size: 16px;
            }

            .site-section h1, .site-section h2, .site-section h3, 
            .site-section p, .site-section ul, .site-section li, 
            .site-section div {
                color: #dcdcdc !important;

            }

            /* Syntax Highlighting */
            .notebook-dark-theme pre, .notebook-dark-theme code {
                background-color: #2d2d2d;
                color: #ffffff !important;
                border: none;
                padding: 10px;
                border-radius: 6px; /* Rounded corners for code blocks */
                white-space: pre-wrap;
                font-family: 'Courier New', Courier, monospace;
            }

            /* Dark theme for tables */
            .notebook-dark-theme table {
                width: 100%;
                background-color: #1e1e1e !important;
                color: #dcdcdc !important;
                border-collapse: collapse;
                border-radius: 6px;
                overflow: hidden;
            }

            .notebook-dark-theme th, .notebook-dark-theme td {
                border: 1px solid #444444 !important;
                padding: 10px;
                text-align: center;
            }

            .notebook-dark-theme th {
                background-color: #1e1e1e !important;
                color: #ffffff !important;
                font-weight: bold;
            }

            .notebook-dark-theme td {
                background-color: #2d2d2d !important;
                color: #dcdcdc !important;
            }

            .notebook-dark-theme tr:nth-child(even) td {
                background-color: #3a3a3a !important;
            }

            /* Additional link styling */
            .notebook-dark-theme a {
                color: #cccccc !important;
                font-size: 16px !important;
                text-decoration: none; 
                transition: color 0.3s ease; 
            }

        `;
        document.head.appendChild(style);
    }

</script>
{% endblock content %}

templates/ml/unsuperv/dbagglokm.html
{% extends "base.html" %}
{% load static %}

{% block content %}

    <div class="site-section notebook-dark-theme">
        
        <div class="container-wrapper">
            <!-- Sidebar section -->
            <div class="sidebar-container">
                {% include 'sidebar.html' %}
                </div>
            <!-- Main content section -->
            <div class="content-section">
                <div class="container">
                    <div class="row justify-content-center">
                        <div class="col-md-9">
                            <h2 class="h3 mb-3">Python Code Example</h2>
                            <div id="notebook-container" class="notebook-card">
                                <!-- Notebook content will be injected here -->
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

<script src="https://cdn.plot.ly/plotly-latest.min.js"></script>
<script>
    // document.addEventListener('DOMContentLoaded', function() {
    //     // Use AJAX to fetch the notebook HTML and inject it into the div
    //     fetch("{% url 'ml:notebook-db-agglo-km' %}")
    //         .then(response => response.text())
    //         .then(html => {
    //             document.getElementById('notebook-container').innerHTML = html;

    //             // Apply dark theme CSS after notebook is loaded
    //             applyDarkTheme();
    //         })
    //         .catch(error => {
    //             console.error('Error fetching notebook HTML:', error);
    //         });
    // });
    document.addEventListener('DOMContentLoaded', function() {
        // Use AJAX to fetch the notebook HTML and inject it into the div
        fetch("{% url 'ml:notebook-db-agglo-km' %}")
            .then(response => response.text())
            .then(html => {
                // Inject the HTML into the notebook container
                document.getElementById('notebook-container').innerHTML = html;

                // Apply dark theme CSS after notebook is loaded
                applyDarkTheme();

                // Re-run Plotly rendering scripts after the notebook is loaded
                renderPlotly();
            })
            .catch(error => {
                console.error('Error fetching notebook HTML:', error);
            });
    });

    function applyDarkTheme() {
        // Add specific dark theme styles for the notebook
        const style = document.createElement('style');
        style.innerHTML = `
            /* Dark Theme Styling for Notebook */
            .notebook-dark-theme {
                background-color: #1e1e1e;
                color: #dcdcdc !important;
                padding: 20px;
                border-radius: 10px;
                box-shadow: 0 4px 8px rgba(0, 0, 0, 0.3);
                transition: all 0.3s ease-in-out;
                overflow: hidden;
                font-size: 16px;
            }

            .site-section h1, .site-section h2, .site-section h3, 
            .site-section p, .site-section ul, .site-section li, 
            .site-section div {
                color: #dcdcdc !important;

            }

            /* Syntax Highlighting */
            .notebook-dark-theme pre, .notebook-dark-theme code {
                background-color: #2d2d2d;
                color: #ffffff !important;
                border: none;
                padding: 10px;
                border-radius: 6px; /* Rounded corners for code blocks */
                white-space: pre-wrap;
                font-family: 'Courier New', Courier, monospace;
            }

            /* Dark theme for tables */
            .notebook-dark-theme table {
                width: 100%;
                background-color: #1e1e1e !important;
                color: #dcdcdc !important;
                border-collapse: collapse;
                border-radius: 6px;
                overflow: hidden;
            }

            .notebook-dark-theme th, .notebook-dark-theme td {
                border: 1px solid #444444 !important;
                padding: 10px;
                text-align: center;
            }

            .notebook-dark-theme th {
                background-color: #1e1e1e !important;
                color: #ffffff !important;
                font-weight: bold;
            }

            .notebook-dark-theme td {
                background-color: #2d2d2d !important;
                color: #dcdcdc !important;
            }

            .notebook-dark-theme tr:nth-child(even) td {
                background-color: #3a3a3a !important;
            }

            /* Additional link styling */
            .notebook-dark-theme a {
                color: #cccccc !important;
                font-size: 16px !important;
                text-decoration: none; 
                transition: color 0.3s ease; 
            }

        `;
        document.head.appendChild(style);
    }
    function renderPlotly() {
        // Re-run Plotly's plots by finding all divs with Plotly data
        const plotlyDivs = document.querySelectorAll('.plotly-graph-div');
        plotlyDivs.forEach(function (div) {
            const plotData = JSON.parse(div.dataset.plotData);
            const layout = JSON.parse(div.dataset.plotLayout);
            Plotly.newPlot(div, plotData, layout);
        });
    }
</script>
{% endblock content %}

templates/ml/unsuperv/forest.html
{% extends "base.html" %}
{% load static %}

{% block content %}

    <div class="site-section notebook-dark-theme">
        
        <div class="container-wrapper">
            <!-- Sidebar section -->
            <div class="sidebar-container">
                {% include 'sidebar.html' %}
                </div>
            <!-- Main content section -->
            <div class="content-section">
                <div class="container">
                    <div class="row justify-content-center">
                        <div class="col-md-9">
                            <h2 class="h3 mb-3">Python Code Example</h2>
                            <div id="notebook-container" class="notebook-card">
                                <!-- Notebook content will be injected here -->
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>


<script>
    document.addEventListener('DOMContentLoaded', function() {
        // Use AJAX to fetch the notebook HTML and inject it into the div
        fetch("{% url 'ml:notebook-isoforest' %}")
            .then(response => response.text())
            .then(html => {
                document.getElementById('notebook-container').innerHTML = html;

                // Apply dark theme CSS after notebook is loaded
                applyDarkTheme();
            })
            .catch(error => {
                console.error('Error fetching notebook HTML:', error);
            });
    });


    function applyDarkTheme() {
        // Add specific dark theme styles for the notebook
        const style = document.createElement('style');
        style.innerHTML = `
            /* Dark Theme Styling for Notebook */
            .notebook-dark-theme {
                background-color: #1e1e1e;
                color: #dcdcdc !important;
                padding: 20px;
                border-radius: 10px;
                box-shadow: 0 4px 8px rgba(0, 0, 0, 0.3);
                transition: all 0.3s ease-in-out;
                overflow: hidden;
                font-size: 16px;
            }

            .site-section h1, .site-section h2, .site-section h3, 
            .site-section p, .site-section ul, .site-section li, 
            .site-section div {
                color: #dcdcdc !important;

            }

            /* Syntax Highlighting */
            .notebook-dark-theme pre, .notebook-dark-theme code {
                background-color: #2d2d2d;
                color: #ffffff !important;
                border: none;
                padding: 10px;
                border-radius: 6px; /* Rounded corners for code blocks */
                white-space: pre-wrap;
                font-family: 'Courier New', Courier, monospace;
            }

            /* Dark theme for tables */
            .notebook-dark-theme table {
                width: 100%;
                background-color: #1e1e1e !important;
                color: #dcdcdc !important;
                border-collapse: collapse;
                border-radius: 6px;
                overflow: hidden;
            }

            .notebook-dark-theme th, .notebook-dark-theme td {
                border: 1px solid #444444 !important;
                padding: 10px;
                text-align: center;
            }

            .notebook-dark-theme th {
                background-color: #1e1e1e !important;
                color: #ffffff !important;
                font-weight: bold;
            }

            .notebook-dark-theme td {
                background-color: #2d2d2d !important;
                color: #dcdcdc !important;
            }

            .notebook-dark-theme tr:nth-child(even) td {
                background-color: #3a3a3a !important;
            }

            /* Additional link styling */
            .notebook-dark-theme a {
                color: #cccccc !important;
                font-size: 16px !important;
                text-decoration: none; 
                transition: color 0.3s ease; 
            }

        `;
        document.head.appendChild(style);
    }

</script>
{% endblock content %}